# Generated by Django 4.2.1 on 2024-11-14 22:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertsResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('opinion_weight', models.FloatField()),
                ('expert_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts_responses', to='questionnaire.tasks')),
            ],
        ),
    ]
