# Generated by Django 4.2.1 on 2024-11-19 20:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertsresponses',
            name='answers',
        ),
        migrations.AddField(
            model_name='expertsresponses',
            name='parameters_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='expertsresponses',
            name='str_convolution',
            field=models.TextField(blank=True),
        ),
    ]
