# Generated by Django 4.2.1 on 2024-11-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_remove_user_fio_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
